ARG BASE_IMAGE="docker.io/astropatty/mpi4py:mpich-4.1.2-py3.13"
FROM ${BASE_IMAGE}

ARG HDF5_VERSION="2.1.1"
ARG HDF5_URL="https://github.com/HDFGroup/hdf5/archive/refs/tags/2.1.1.tar.gz"

RUN apt-get update && apt-get -y install wget

WORKDIR /install
RUN wget -O hdf5.tar.gz ${HDF5_URL} \
    && tar -xvzf hdf5.tar.gz \
    && mv hdf5-${HDF5_VERSION} hdf5

WORKDIR /install/hdf5
RUN CC=/mpich/install/bin/mpicc ./configure --prefix /usr/local --enable-parallel \
    && make -j4 \
    && make install

WORKDIR /app
RUN rm -rf /install

RUN CC=/mpich/install/bin/mpicc HDF5_MPI="ON" HDF5_DIR="/usr/local" \
    uv pip install --no-binary=h5py h5py
