ARG BASE_IMAGE="docker.io/astropatty/mpich:mpich-4.1.2"
FROM ${BASE_IMAGE}

ARG PYTHON_VERSION="3.13"

ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN UV_INSTALL_DIR=/usr/local/bin sh /uv-installer.sh && rm /uv-installer.sh
RUN uv venv --python ${PYTHON_VERSION} /opt/venv

ENV VIRTUAL_ENV=/opt/venv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN MPICC=/mpich/install/bin/mpicc uv pip install mpi4py
