ARG BASE_IMAGE="docker.io/astropatty/mpi4py:mpich-4.1.2-py3.13"
FROM ${BASE_IMAGE}

ARG HDF5_VERSION="2.1.1"
ARG HDF5_URL="https://github.com/HDFGroup/hdf5/archive/refs/tags/2.1.1.tar.gz"

RUN apt-get update && apt-get -y install cmake wget

WORKDIR /install
RUN wget -O hdf5.tar.gz ${HDF5_URL} \
    && tar -xvzf hdf5.tar.gz \
    && mv hdf5-${HDF5_VERSION} hdf5

WORKDIR /install/hdf5
RUN cmake -B build \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DHDF5_ENABLE_PARALLEL=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=/mpich/install/bin/mpicc \
    && cmake --build build -j4 \
    && cmake --install build

WORKDIR /app
RUN rm -rf /install

RUN CC=/mpich/install/bin/mpicc HDF5_MPI="ON" HDF5_DIR="/usr/local" \
    uv pip install --no-binary=h5py h5py
